server:
  port: 8093

spring:
  application:
    name: ATTENDANCE-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27023/reactive-microservices-attendance
      gridfs:
        database: files
        bucket: images
      auto-index-creation: true
  webflux:
    problemdetails:
      enabled: true

logging:
  level:
    root: info
    web: debug

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
