version: '3.8'
services:
  mongodb_user_service:
    image: mongo:7.0.4
    container_name: reactive-microservices-mongodb-user-service
    volumes:
      - data_user_service:/data/db
    ports:
      - "27021:27017"

  mongodb_event_service:
    image: mongo:7.0.4
    container_name: reactive-microservices-mongodb-event-service
    volumes:
      - data_event_service:/data/db
    ports:
      - "27022:27017"

  postgres_attendance_service:
    image: postgres:15.5
    container_name: reactive-microservices-postgres-attendance-service
    restart: always
    environment:
      POSTGRES_DB: attendance-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - data_attendance_service:/var/lib/postgresql/data

volumes:
  data_user_service:
  data_event_service:
  data_attendance_service: