server:
  port: 8091

spring:
  application:
    name: USER-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27020/reactive-microservices-mongodb
      gridfs:
        database: files
        bucket: images
      auto-index-creation: true
  webflux:
    problemdetails:
      enabled: true

logging:
  level:
    root: info
    web: debug

jwt:
  secret: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALag2jFucjXRNO6UzOd8nOmviyYMZ5NGD7YO1lQF3sFfkDtooeWuMY5DNi4YQSLhUJ2Zqmea9+lQsOK3UG/W2IsCAwEAAQ==

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/