server:
  port: 8092

spring:
  application:
    name: EVENT-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27022/reactive-microservices-event
      gridfs:
        database: files
        bucket: images
      auto-index-creation: true
  webflux:
    problemdetails:
      enabled: true

logging:
  level:
    root: info
    web: debug

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
